inherit_from:
  - ./config/rubocop.relaxed.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - .gems/**/*

Rails:
  Enabled: true

Style/AndOr:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Rails/Validation:
  Enabled: false

SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/BlockComments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
  Enabled: true

Metrics/ModuleLength:
  CountComments: false
  Max: 100
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'db/schema.rb'